[package]
name = "openresponses"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3"
progenitor = "0.11"
reqwest = { version = "0.12", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
